import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });
import { neobrutalism } from "@clerk/themes";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{theme: neobrutalism}} >
      <html
       lang="en" suppressHydrationWarning>
       <body className={inter.className}>
        <Header/>
         <main className="min-h-screen">{children}</main>

         <footer className="py-8 px-4 border-t">
           <div className="max-w-6xl mx-auto flex justify-center items-center">
             <p className="text-stone-500 text-sm">
              made by Aliyaan
               </p>
            </div>
          </footer>
         </body>
       </html>
     </ClerkProvider>
  );
}
